// Auto-generated by scripts/build-sidecar.ts
// Do not edit manually - this file is generated during build

export const VERSION = {
  git_commit: "aefe9c8",
  git_describe: "aefe9c8",
  buildTime: "2026-02-13T23:37:51.984Z",
};
